<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.597" timestamp="2020-12-09T14:12:35.961297" hostname="LTNL000052"><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 257, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 313, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 338, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 110, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 121, in runtestprotocol
    rep = call_and_report(item, "setup", log)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 218, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)  # type: TestReport
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\153841\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\Users\153841\PycharmProjects\pythonSelFramework\tests\conftest.py", line 60, in pytest_runtest_makereport
    _capture_screenshot(file_name)
  File "C:\Users\153841\PycharmProjects\pythonSelFramework\tests\conftest.py", line 68, in _capture_screenshot
    driver.get_screenshot_as_file(name)
AttributeError: 'NoneType' object has no attribute 'get_screenshot_as_file'</error></testcase></testsuite></testsuites>